# Generated by Django 3.2.9 on 2021-11-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
