# Generated by Django 3.2.9 on 2021-11-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_active',
        ),
        migrations.AddField(
            model_name='card',
            name='activation_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='INACTIVE', max_length=200),
        ),
    ]
