# Generated by Django 3.2.9 on 2021-11-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='INACTIVE', max_length=200),
        ),
    ]
