# Generated by Django 3.2.9 on 2021-12-13 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20211128_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcollection',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
